### ISSUE TITLE
Application hangs when opened

### ISSUE THREAD

**Issue by Amplifi-Beats** [gianxddddd/ArchoMusic#8]
I have it installed along the last java release and the kotlin version hangs on startup, the system UI reports it as "Archo Music has stopped working" and it force closes.
Deleting cache, force stopping and reinstalling doesn't work

**Comment by gianxddddd** [comment]
What's your device's Android version?

**Comment by Amplifi-Beats** [comment]
10 (Q)

**Comment by gianxddddd** [comment]
That might be the storage permissions, you have to allow them through Device Settings.
